default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: profit_calculator_development
  url: <%= ENV['DEV_DB'] %>

staging:
  <<: *default
  url: <%= ENV['STAGE_DB'] %>

test:
  <<: *default
  database: profit_calculator_test

production:
  <<: *default
  url: <%= ENV['PROD_DB'] %>
